ManagerTracker/Models/WorkOrders.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ManagerTracker.Models
{
    public class WorkOrders
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string PartQuantity { get; set; }
        public string PartPrice { get; set; }
        public string PartNumberOrDescription { get; set; }
        public string RepairDescription { get; set; }

        [ForeignKey("Mechanics")]
        public int MechanicsId { get; set; }
        public Mechanics Mechanics { get; set; }

        [ForeignKey("Trucks")]
        public int? TrucksId { get; set; }
        public Trucks Trucks { get; set; }

        [ForeignKey("Trailers")]
        public int? TrailersId { get; set; }
        public Trailers Trailers { get; set; }
    }
}

ManagerTracker/Controllers/TrailerController.cs
using ManagerTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerTracker.Controllers
{
    public class TrailerController : Controller
    {
        ApplicationDbContext db;
        public TrailerController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Trailer
        public ActionResult Index()
        {
            var trailers = db.Trailers;
            return View(trailers.ToList());
        }

        // GET: Trailer/Details/5
        public ActionResult Details(int id)
        {
            return View(db.Trailers.Find(id));
        }

        // GET: Trailer/Create
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Trailers, "Id", "Number");
            return View();
        }

        // POST: Trailer/Create
        [HttpPost]
        public ActionResult Create(Trailers trailers)
        {
            try
            {
                db.Trailers.Add(trailers);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Trailer/Edit/5
        public ActionResult Edit(int id)
        {
            List<Trailers> ListofTrailers = db.Trailers.ToList();
            return View();
        }

        // POST: Trailer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, Trailers trailers)
        {
            try
            {
                // TODO: Add update logic here
                Trailers thistrailers = db.Trailers.Find(id);
                thistrailers.Number = trailers.Number;
                thistrailers.Year = trailers.Year;
                thistrailers.Make = trailers.Make;
                thistrailers.Model = trailers.Model;
                thistrailers.Vin = trailers.Vin;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Trailer/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.Trailers.Find(id));
        }

        // POST: Trailer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                db.Trailers.Remove(db.Trailers.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ManagerTracker/Controllers/TruckController.cs
using ManagerTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerTracker.Controllers
{
    public class TruckController : Controller
    {
        ApplicationDbContext db;
        public TruckController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Truck
        public ActionResult Index()
        {
            var trucks = db.Trucks;
            return View(trucks.ToList());
        }

        // GET: Truck/Details/5
        public ActionResult Details(int id)
        {
            return View(db.Trucks.Find(id));
        }

        // GET: Truck/Create
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Trucks, "Id", "Number");
            return View();
        }

        // POST: Truck/Create
        [HttpPost]
        public ActionResult Create(Trucks trucks)
        {
            try
            {
                // TODO: Add insert logic here
                db.Trucks.Add(trucks);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Truck/Edit/5
        public ActionResult Edit(int id)
        {
            List<Trucks> ListofTrucks = db.Trucks.ToList();
            return View();
        }

        // POST: Truck/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection,Trucks trucks)
        {
            try
            {
                // TODO: Add update logic here
                Trucks thisTrucks = db.Trucks.Find(id);
                thisTrucks.Number = trucks.Number;
                thisTrucks.Year = trucks.Year;
                thisTrucks.Make = trucks.Make;
                thisTrucks.Model = trucks.Model;
                thisTrucks.Vin = trucks.Vin;
                thisTrucks.EngineSerialNumber = trucks.EngineSerialNumber;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Truck/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.Trucks.Find(id));
        }

        // POST: Truck/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                db.Trucks.Remove(db.Trucks.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ManagerTracker/Controllers/WorkOrderController.cs
using ManagerTracker.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ManagerTracker.Controllers
{
    public class WorkOrderController : Controller
    {
        ApplicationDbContext db;
        public WorkOrderController()
        {
            db = new ApplicationDbContext();
        }
        // GET: WorkOrder
        public ActionResult Index(string searchBy, string search, string FirstName)
        {
            var workOrders = db.WorkOrders.ToList();
            foreach (WorkOrders workorder in workOrders)
            {
                //{
                workorder.Trucks = db.Trucks.Where(p => p.Id == workorder.TrucksId).Single();
                workorder.Trailers = db.Trailers.Where(s => s.Id == workorder.TrailersId).Single();
                workorder.Mechanics = db.Mechanics.Where(m => m.Id == workorder.MechanicsId).Single();
                //}
                if (searchBy == "FirstName")
                {
                    var workOrder = db.WorkOrders.Where(m => m.Mechanics.FirstName == search).ToList();
                    foreach (WorkOrders order in workOrder)
                    {
                        order.Trucks = db.Trucks.Where(t => t.Id == order.TrucksId).Select(t => t).Single();
                        order.Trailers = db.Trailers.Where(r => r.Id == order.TrailersId).Select(r => r).Single();
                        order.Mechanics = db.Mechanics.Where(m => m.Id == order.MechanicsId).Select(m => m).Single();
                    }
                        return View(workOrder);
                }
                if (searchBy == "TruckNumber")
                {
                    var workOrder = db.WorkOrders.Where(p => p.Trucks.Number == search).ToList();
                    foreach (WorkOrders order in workOrder)
                    {
                        order.Mechanics = db.Mechanics.Where(m => m.Id == order.MechanicsId).Select(m => m).Single();
                        order.Trucks = db.Trucks.Where(t => t.Id == order.TrucksId).Select(t => t).Single();
                        order.Trailers = db.Trailers.Where(r => r.Id == order.TrailersId).Select(r => r).Single();
                    }

                    return View(workOrder);
                }
                if (searchBy == "TrailerNumber")
                {
                    var workOrder = db.WorkOrders.Where(s => s.Trailers.Number == search).ToList();
                    foreach (WorkOrders order in workOrder)
                    {
                        order.Mechanics = db.Mechanics.Where(m => m.Id == order.MechanicsId).Select(m => m).Single();
                        order.Trailers = db.Trailers.Where(r => r.Id == order.TrailersId).Select(r => r).Single();
                        order.Trucks = db.Trucks.Where(t => t.Id == order.TrucksId).Select(t => t).Single();
                    }
                        return View(workOrder);
                }
            }
            return View(workOrders);
        }

        // GET: WorkOrder/Details/5
        public ActionResult Details(int id, int? MechanicsId, string TrucksId, string TrailersId, WorkOrders workOrder)
        {
            try
            {
                //var mechanic = db.Mechanics.Single(m => m.Id == id);
                //
                //ViewBag.MechanicsId = new SelectList(db.Mechanics.ToList(), "Id", "FirstName");
                //ViewBag.TrucksId = new SelectList(db.Trucks.Select(t => t.Number));
                //ViewBag.TrailersId = new SelectList(db.Trailers.Select(r => r.Number));
                //ViewBag.MechanicsId = new SelectList(db.Mechanics.Select(m => m.FirstName));
                //ViewBag.Mechanics = db.Mechanics.Where(m => m.Id).Select(m => m.FirstName);

                //workOrders.TrucksId = db.Trucks.Where(t => t.Number == TrucksId).Single().Id;
                //workOrders.TrailersId = db.Trailers.Where(r => r.Number == TrailersId).Single().Id;
                //workOrders.MechanicsId = db.Mechanics.Where(m => m.FirstName == FirstName).Single().Id;

                workOrder.Trucks = db.Trucks.Where(p => p.Id == workOrder.TrucksId).Single();
                workOrder.Trailers = db.Trailers.Where(s => s.Id == workOrder.TrailersId).Single();
                workOrder.Mechanics = db.Mechanics.Where(m => m.Id == workOrder.MechanicsId).Single();

                return View(db.WorkOrders.Find(id));
                //var workOrder = db.WorkOrders.Single(w => w.Id == id);
                //return View(workOrder);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            
        }

        // GET: WorkOrder/Create
        public ActionResult Create()
        {
            ViewBag.MechanicsId = new SelectList(db.Mechanics.Select(m => m.FirstName));
            // ViewBag.MechanicsId = new SelectList(db.Mechanics.ToList(), "Id", "FirstName");
            ViewBag.TrucksId = new SelectList(db.Trucks.Select(t=> t.Number));
            ViewBag.TrailersId = new SelectList(db.Trailers.Select(r=> r.Number));
            return View();
        }

        // POST: WorkOrder/Create
        [HttpPost]
        public ActionResult Create(WorkOrders workOrders, int MechanicsId, string TrucksId, string TrailersId, string FirstName)
        {
            workOrders.TrucksId = db.Trucks.Where(t => t.Number == TrucksId).Single().Id;
            workOrders.TrailersId = db.Trailers.Where(r => r.Number == TrailersId).Single().Id;
            //workOrders.MechanicsId = MechanicsId;
            workOrders.MechanicsId = db.Mechanics.Where(m => m.FirstName == FirstName).Single().Id;
            if (true)
            {
                db.WorkOrders.Add(workOrders);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                foreach (var obj in ModelState.Values)
                {
                    foreach (var error in obj.Errors)
                    {
                        if (!string.IsNullOrEmpty(error.ErrorMessage))
                            System.Diagnostics.Debug.WriteLine("ERROR WHY = " + error.ErrorMessage);
                    }
                }
            }
            
            {
                return View();
            }

            return View();
        }

        // GET: WorkOrder/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrders @workOrders = db.WorkOrders.Find(id);
            if (@workOrders == null)
            {
                return HttpNotFound();
            }
            ViewBag.MechanicsId = new SelectList(db.Mechanics.Select(m => m.FirstName));
            ViewBag.TrucksId = new SelectList(db.Trucks.Select(t => t.Number));
            ViewBag.TrailersId = new SelectList(db.Trailers.Select(r => r.Number));
            return View();
        }

        // POST: WorkOrder/Edit/5
        [HttpPost]
        public ActionResult Edit(int MechanicsId, string TrucksId, string TrailersId, string FirstName, [Bind(Include = "Id,Date,StartTime,EndTime,PartQuantity,PartPrice,PartNumberOrDescription,RepairDescription,MechanicsId,TrucksId,TrailersId")]WorkOrders @workOrders)
        {
            workOrders.TrucksId = db.Trucks.Where(t => t.Number == TrucksId).Single().Id;
            workOrders.TrailersId = db.Trailers.Where(r => r.Number == TrailersId).Single().Id;
            workOrders.MechanicsId = db.Mechanics.Where(m => m.FirstName == FirstName).Single().Id;
            if (true)
            {
                db.Entry(@workOrders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: WorkOrder/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.WorkOrders.Find(id));
        }

        // POST: WorkOrder/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                db.WorkOrders.Remove(db.WorkOrders.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Search(string searching, Mechanics mechanics)
        {
            //var workOrders = db.WorkOrders.ToList();
            //foreach (WorkOrders workorder in workOrders)
            //{
            //    workorder.Trucks = db.Trucks.Where(p => p.Id == workorder.TrucksId).Single();
            //    workorder.Trailers = db.Trailers.Where(s => s.Id == workorder.TrailersId).Single();
            //    workorder.Mechanics = db.Mechanics.Where(m => m.Id == workorder.MechanicsId).Single();
            //}
            //return View(workOrders);
            //return View(db.WorkOrders.Where(x => x.MechanicsId.Contains(searching) || searching == null).ToList());
            //ViewBag.MechanicsId = from m in db.WorkOrders
            //var mechanics = from m in db.WorkOrders
            //                select m;
            //if (!String.IsNullOrEmpty(searching))
            //{
            //    //ViewBag.MechanicsId = mechanics.Where(db.Mechanics.Select(m => m.FirstName)).Contains(searching);
            //    mechanics = db.Mechanics.Where(m => m.FirstName.Contains(searching));
            //}


            return View();
        }

        [HttpPost]
        public ActionResult Search(WorkOrders workOrders,int MechanicsId, string TrucksId, string TrailersId, string FirstName)
        {

ManagerTracker/Views/WorkOrder/Create.cshtml
@model ManagerTracker.Models.WorkOrders

@{
    ViewBag.Title = "Create";
}

<h2>-WorkOrder Create-</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartNumberOrDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNumberOrDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNumberOrDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RepairDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepairDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepairDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MechanicsId, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MechanicsId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownList("MechanicsId", ViewBag.MechanicsId);*@

                @Html.ValidationMessageFor(model => model.MechanicsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrucksId, "Truck Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrucksId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrucksId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrailersId, "Trailer number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrailersId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrailersId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ManagerTracker/Views/WorkOrder/Delete.cshtml
@model ManagerTracker.Models.WorkOrders

@{
    ViewBag.Title = "Delete";
}

<h2>-WorkOrder Delete-</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mechanics.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mechanics.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trailers.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trailers.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trucks.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trucks.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartNumberOrDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumberOrDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RepairDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepairDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
</div>

ManagerTracker/Views/WorkOrder/Details.cshtml
@model ManagerTracker.Models.WorkOrders

@{
    ViewBag.Title = "Details";
}

<h2>-WorkOrder Details-</h2>

<div>
    @*<ul>
        <li>Name: @Model.Mechanics.FirstName</li>
        <li>Trailer Number: @Model.Trailers.Number</li>
        <li>Truck Number: @Model.Trucks.Number</li>
        <li>Date: @Model.Date</li>
        <li>Start Time: @Model.StartTime</li>
        <li>End Time: @Model.EndTime</li>
        <li>Part Number or Description: @Model.PartNumberOrDescription</li>
        <li>Part Quantities: @Model.PartQuantity</li>
        <li>Part Prices: @Model.PartPrice</li>
        <li>Repair Story: @Model.RepairDescription</li>
    </ul>*@
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.Mechanics.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mechanics.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trailers.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trailers.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trucks.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trucks.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartNumberOrDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumberOrDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RepairDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepairDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ManagerTracker/Views/WorkOrder/Index.cshtml
@model IEnumerable<ManagerTracker.Models.WorkOrders>

@{
    ViewBag.Title = "Index";
}

<h2>-WorkOrders-</h2>

<p>
    @Html.ActionLink("Create New |", "Create")
    @*@Html.ActionLink("Search |", "Search")*@
    @Html.ActionLink("List of Trailers |", "Index", "Trailer")
    @Html.ActionLink("List of Trucks", "Index", "Truck")

</p>
<p>
    @using (Html.BeginForm("Index", "WorkOrder", FormMethod.Get))
    {
        <b>Search By:</b> @Html.RadioButton("searchBy", "FirstName", true) <text>Mechanic</text>
        @Html.RadioButton("searchBy", "TruckNumber") <text>Truck</text>
        @Html.RadioButton("searchBy", "TrailerNumber") <text>Trailer</text><br />
        @Html.TextBox("search") <input type="submit" value="search" />
    }
   
</p>
<table class="table">
    <thead>
        <tr>
            <th rowspan=4>First Name</th>
            <th rowspan=4>Trailer Number</th>
            <th rowspan=4>Truck Number</th>
            <th rowspan=4>Date</th>
            <th rowspan=4>Start Time</th>
            <th rowspan=4>End Time</th>
            <th rowspan=4>Part Number or Description</th>
            <th rowspan=4>Part Quantities</th>
            <th rowspan=4>Part Price</th>
            <th rowspan=4>Repair Story</th>
        </tr>
    </thead>
    @*<tr>
            <th>
                @Html.DisplayNameFor(model => model.Mechanics.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trailers.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trucks.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartNumberOrDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartQuantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepairDescription)
            </th>
            <th></th>
        </tr>*@

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Mechanics.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trailers.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trucks.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartNumberOrDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RepairDescription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>

    }

</table>